apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
  - name: postgres
     #for postgres, we need to pass in username and password environment variables
    image: postgres:15-alpine
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
    ports:
      #by default postgres listens on port 5432
      - containerPort: 5432
        name: postgres
