apiVersion: v1
kind: Deployment
metadata:
  name: redis
  labels:
     app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        # name is redis service
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
          #by default redis listens on port 6379
          - containerPort: 6379
            name: redis

      