apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    # name is redis service
    app: redis
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
      #by default redis listens on port 6379
      - containerPort: 6379
        name: redis
